name: h2_tracker_server
description: Starting point for a Serverpod server.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 2.1.4
  path: ^1.9.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  lints: '>=3.0.0 <5.0.0'
